### ISSUE TITLE
error compiling libcurve

### ISSUE THREAD

**Issue by xzhaous** [zeromq/libcurve#17]
I followed all the installation procedure and I got following error. anyone can help out?

gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

make check
Making check in src
make[1]: Entering directory `/root/libcurve/src'
/bin/sh ../libtool --tag=CC   --mode=compile gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../include  -pedantic -Werror -Wall -D_GNU_SOURCE -DLINUX -D_REENTRANT -D_THREAD_SAFE   -g -O2 -MT curve_client.lo -MD -MP -MF .deps/curve_client.Tpo -c -o curve_client.lo curve_client.c
libtool: compile:  gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I../include -pedantic -Werror -Wall -D_GNU_SOURCE -DLINUX -D_REENTRANT -D_THREAD_SAFE -g -O2 -MT curve_client.lo -MD -MP -MF .deps/curve_client.Tpo -c curve_client.c  -fPIC -DPIC -o .libs/curve_client.o
curve_client.c: In function 'curve_client_new':
curve_client.c:68:5: error: too many arguments to function 'zstr_sendm'
/usr/include/zstr.h:37:5: note: declared here
curve_client.c: In function 'curve_client_set_verbose':
curve_client.c:126:5: error: too many arguments to function 'zstr_send'
/usr/include/zstr.h:32:5: note: declared here
curve_client.c: In function 's_agent_new':
curve_client.c:253:5: error: format not a string literal and no format arguments [-Werror=format-security]
curve_client.c: In function 's_agent_handle_control':
curve_client.c:308:9: error: format not a string literal and no format arguments [-Werror=format-security]
curve_client.c:318:13: error: format not a string literal and no format arguments [-Werror=format-security]
cc1: all warnings being treated as errors
make[1]: *** [curve_client.lo] Error 1
make[1]: Leaving directory`/root/libcurve/src'
make: **\* [check-recursive] Error 1

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libcurve/pull/18
