### ISSUE TITLE
Wrong Key used for generating Vouch in INITATE message

### ISSUE THREAD

**Issue by dbo-amadis** [zeromq/libcurve#19]
Fix #14 introduced an error while generating the vouch for INITIATE Message
vouch-box = Box [C',S](C->S')
The actual code is using the precomputed key --> Box [C',S](C'->S') therefore there's no way of validating the Client's Permanent Secret Key

To fix the issue

Line 627:
    s_encrypt (self, vouch_crypt,
               vouch_plain, 64,
               "VOUCH---",
               NULL, NULL);

Should be replaced with:
    s_encrypt (self, vouch_crypt,
               vouch_plain, 64,
               "VOUCH---",
               self->peer_transkey, zcert_secret_key (self->permacert));

Line 704:
        int rc = s_decrypt (self,
            vouch,
            plain, 64,
            "VOUCH---",
            NULL, NULL);

Should be replaced with:
        int rc = s_decrypt (self,
            vouch,
            plain, 64,
            "VOUCH---",
            self->peer_permakey,  zcert_secret_key(self->transcert));

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libcurve/pull/18
