### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by krombel** [zeromq/libcurve#28]
I got an issue compiling the current master of libcurve

I pushed my console-output to gist for review:
https://gist.github.com/krombel/8490f556d784bbf67ce5

libsodium, libzmq and czmq were installed previously and could be tested with small examples

I was testing with linuxmint 17.3 and debian 8

Thank you for you help.

**Comment by hintjens** [comment]
It should work now. Thanks for reporting this.

**Comment by krombel** [comment]
Thank you for fixing this that quickly. Building succeeded.

**Comment by hintjens** [comment]
With pleasure.

**Comment by krombel** [comment]
hmm... I don't know it this was there today afternoon but during further development I noticed that the selftest after building fails. First I was focused on the output of the Testsuite which shows no error.

I copied my output here: https://gist.github.com/krombel/948e2ac7db9124ec8724

Hopefully you are able to resolve this issue.

**Comment by photoszzt** [comment]
Is there any update on this issue?

**Comment by hintjens** [comment]
Sorry for the slow response on this. It should work properly now.

**Comment by photoszzt** [comment]
It's still broken: https://travis-ci.org/zeromq/libcurve/builds/112617225

**Comment by hintjens** [comment]
Does it give the same error when you build manually? There's something
wrong with the .travis script, I think.

**Comment by photoszzt** [comment]
Yes. I'm building the libraries installed in directory inside $HOME and I'm using the cmake file. 

Here is the cmake command line I'm using: 

cmake .. -DLIBZMQ_LIBRARIES=$PREFIX/lib/libzmq.so -DLIBZMQ_INCLUDE_DIRS=$PREFIX/include  -DCZMQ_LIBRARIES=$PREFIX/lib/libczmq.so -DCZMQ_INCLUDE_DIRS=$PREFIX/include -DCMAKE_INSTALL_PREFIX=$PREFIX

This is what I get: https://gist.github.com/photoszzt/9e2ffa63a6a316d29d6c for cmake output. 

Apparently the curve_source is empty in this case, then I add the ENABLE_DRAFTS at the end: 

cmake .. -DLIBZMQ_LIBRARIES=$PREFIX/lib/libzmq.so -DLIBZMQ_INCLUDE_DIRS=$PREFIX/include  -DCZMQ_LIBRARIES=$PREFIX/lib/libczmq.so -DCZMQ_INCLUDE_DIRS=$PREFIX/include -DCMAKE_INSTALL_PREFIX=$PREFIX -DENABLE_DRAFTS=yes

This configuration solves the linker language problem. 

The output of make is: https://gist.github.com/photoszzt/54d7c6192df796d33e1e

**Comment by photoszzt** [comment]
I have been using cmake method to build czmq and libzmq successfully and they all install in a directory under $HOME.

**Comment by hintjens** [comment]
OK, I've made another change to the project spec. Libsodium wasn't
explicitly listed as a dependency, which caused the link errors.

**Comment by photoszzt** [comment]
I can build successfully with this version of cmake file. But I still get the assertion error: 
https://gist.github.com/photoszzt/73b27f713550aaabfadf

**Comment by hintjens** [comment]
I've tracked this down to what looks like a new error return in libsodium.
It hits a test case where we pass an invalid key (on purpose). I'm
double-checking, and will have a fix soon.

**Comment by hintjens** [comment]
OK, fixed on libcurve master now. Thanks for your patience.

**Comment by photoszzt** [comment]
@hintjens I see. Since you bring up libsodium, there is similar issue on the libzmq when I build with CMake with libsodium enable which makes some tests fail but the build with tweetnacl seems fine.

**Comment by hintjens** [comment]
I fixed this in libzmq master, at the same time. If you can catch any
failing tests on current master, please let me know.

**Comment by photoszzt** [comment]
OK, I will command on the libzmq issue.

**Comment by hintjens** [comment]
Thanks
