### ISSUE TITLE
error compiling libcurve

### ISSUE THREAD

**Issue by eyalb39** [zeromq/libcurve#33]
I followed the instructions, however it fails for me on the the checking stage.
My environment is:  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
The error seem a bit trivial related to byte_/const byte_, but I'd rather don't touch as I'm not familiar with the module internals.
I copy from the relevant part of the checks, the error I get is:

configure: ENABLE_CURVE_SELFTEST defined
checking return type of signal handlers... void
checking for perror... yes
checking for gettimeofday... yes
checking for memset... no
checking for getifaddrs... yes
configure: Building stable and legacy API + draft API
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/libcurve.pc
config.status: creating src/platform.h
config.status: src/platform.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in doc
make[1]: Entering directory '/home/test/workspace/libcurve/doc'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/test/workspace/libcurve/doc'
make[1]: Entering directory '/home/test/workspace/libcurve'
  CC       src/src_libcurve_la-curve_client.lo
src/curve_client.c: In function ‘curve_client_test’:
src/curve_client.c:521:59: error: passing argument 3 of ‘curve_client_connect’ discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
     curve_client_connect (client, "tcp://127.0.0.1:9005", zcert_public_key (ser
                                                           ^
src/curve_client.c:123:1: note: expected ‘byte \* {aka unsigned char _}’ but argument is of type ‘const byte \* {aka const unsigned char *}’
 curve_client_connect (curve_client_t *self, char *endpoint, byte *server_key)
 ^
cc1: all warnings being treated as errors
Makefile:922: recipe for target 'src/src_libcurve_la-curve_client.lo' failed
make[1]: *_\* [src/src_libcurve_la-curve_client.lo] Error 1
make[1]: Leaving directory '/home/test/workspace/libcurve'
Makefile:1022: recipe for target 'all-recursive' failed
make: **\* [all-recursive] Error 1

**Comment by bluca** [comment]
Fixed by https://github.com/zeromq/libcurve/pull/36
