### ISSUE TITLE
Unable to build latest libcurve on Ubuntu 16.04

### ISSUE THREAD

**Issue by FarooqKhan** [zeromq/libcurve#38]
I followed the steps in the README.md

All the required dependency (libsodium, libzmq, czmq) are latest. Am able to build upto czmq, however libcurve build fails with error: **configure: error: cannot link with -lczmq, install libczmq**

config.log shows the following error:

configure:13007: checking for pkg-config
configure:13025: found /usr/bin/pkg-config
configure:13037: result: /usr/bin/pkg-config
configure:13062: checking pkg-config is at least version 0.9.0
configure:13065: result: yes
configure:13174: checking for libzmq
configure:13181: $PKG_CONFIG --exists --print-errors "libzmq >= 0.0.0"
configure:13184: $? = 0
configure:13198: $PKG_CONFIG --exists --print-errors "libzmq >= 0.0.0"
configure:13201: $? = 0
configure:13383: result: yes
configure:13462: checking for czmq
configure:13486: $PKG_CONFIG --exists --print-errors "libczmq < 4"
Requested 'libczmq < 4' but version of libczmq is 4.0.3
configure:13489: $? = 1
configure:13503: result: no
Requested 'libczmq < 4' but version of libczmq is 4.0.3
configure:13520: Package libczmq not found with needed constraints; falling back to defined compilability tests

Looks like i need to use a older version of libczmq which might further need older version of previous libraries. However before I try that any better workaround??

**Comment by bluca** [comment]
That is correct, you need CZMQ version 3.x as it is enforced by the configure script.

But you do not need to build any dependencies - the correct versions are available in Ubuntu 16.04. So remove any manually built libsodium/libzmq/czmq and run:

```apt-get install libczmq-dev```

Then just run ./configure and it will find everything it needs.

**Comment by FarooqKhan** [comment]
Wow never had such a quick response. Thanks for that. I will follow what you said.
I will close this issue
